name: flexlingua_app
description: "AEducational app for tongue tie (ankyloglossia) awareness and support."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0

  # HTTP Requests
  http: ^1.5.0

  # Screen Responsiveness
  flutter_screenutil: ^5.9.3

  # Google Fonts
  google_fonts: ^6.3.1

  # Routing
  go_router: ^16.2.2
  riverpod_annotation: ^3.0.0
  json_annotation: ^4.9.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_core: ^4.1.0
  flutter_spinkit: ^5.2.2
  rive: ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.7.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/animated-icons.riv
