// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByvu5kJrXTit7Yii-PcYjo1NQF2B_IF0U',
    appId: '1:1011916507295:web:7740fe65e019374a597aaa',
    messagingSenderId: '1011916507295',
    projectId: 'neat-shell-471011-u8',
    authDomain: 'neat-shell-471011-u8.firebaseapp.com',
    storageBucket: 'neat-shell-471011-u8.firebasestorage.app',
    measurementId: 'G-KMLR7ZCMZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbZAeOM-upSHdg9Hm-QO952DfReKGBa8I',
    appId: '1:1011916507295:android:065abb132046b190597aaa',
    messagingSenderId: '1011916507295',
    projectId: 'neat-shell-471011-u8',
    storageBucket: 'neat-shell-471011-u8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlaOASU4p4ENKSfHDVUZQ4mAr-0kRSy5I',
    appId: '1:1011916507295:ios:1eb2a50dd79c4119597aaa',
    messagingSenderId: '1011916507295',
    projectId: 'neat-shell-471011-u8',
    storageBucket: 'neat-shell-471011-u8.firebasestorage.app',
    iosBundleId: 'com.example.flexlinguaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlaOASU4p4ENKSfHDVUZQ4mAr-0kRSy5I',
    appId: '1:1011916507295:ios:1eb2a50dd79c4119597aaa',
    messagingSenderId: '1011916507295',
    projectId: 'neat-shell-471011-u8',
    storageBucket: 'neat-shell-471011-u8.firebasestorage.app',
    iosBundleId: 'com.example.flexlinguaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByvu5kJrXTit7Yii-PcYjo1NQF2B_IF0U',
    appId: '1:1011916507295:web:9545b133e39f83f3597aaa',
    messagingSenderId: '1011916507295',
    projectId: 'neat-shell-471011-u8',
    authDomain: 'neat-shell-471011-u8.firebaseapp.com',
    storageBucket: 'neat-shell-471011-u8.firebasestorage.app',
    measurementId: 'G-QYQ9HCR1G6',
  );
}
